app_lexanar_ru_ip_addr_internal: "10.10.1.36"
db01_lexanar_ru_ip_addr_internal: "10.10.1.25"
db02_lexanar_ru_ip_addr_internal: "10.10.1.26"
entrance_lexanar_ru_ip_addr_external: "130.193.51.191"
gitlab_lexanar_ru_ip_addr_internal: "10.10.1.6"
monitoring_lexanar_ru_ip_addr_internal: "10.10.1.16"
runner_lexanar_ru_ip_addr_internal: "10.10.1.8"